=== JamesPrabu/liblcm/src/SIL.LCModel/Styles.dtd
<!-- Styles.dtd -->
<!--
	Copyright (c) 2014 SIL International
	This software is licensed under the LGPL, version 2.1 or later
	(http://www.gnu.org/licenses/lgpl-2.1.html)
-->
<!-- IMPORTANT NOTE TO MAINTAINERS
	*********************************************************************************************
	ANY change to this DTD must be accompanied by the generation of a new DTDVer guid.
	The DTD version should be changed below, in TeStyles.xml, in FlexStyles.xml, and in StylesXmlAccessor.cs. The
	TE and Flex programs will only work with a stylesheet having the DTD version for which they were created.
	TE and Flex must be modified and recompiled to process a file having an updated DTD. Field personnel
	who do not have the capability to rebuild the software should not modify this file.
	*********************************************************************************************
-->
<!ELEMENT Styles (markup, replacements, ImportMappingSets)>
<!ATTLIST Styles
	date CDATA #REQUIRED
	DTDver (1610190E-D7A3-42D7-8B48-C0C49320435F) #REQUIRED
	label CDATA #IMPLIED
>
<!ELEMENT markup (tag+)>
<!ATTLIST markup
	version CDATA #REQUIRED
>
<!ELEMENT tag (sfm*, sfmchar?, usage*, help?, font, paragraph?)>
<!ATTLIST tag
	id ID #REQUIRED
	guid CDATA #REQUIRED
	userlevel (0 | 1 | 2 | 3 | 4 | 5) #REQUIRED
	context (annotation | back | backTranslation | book | general | internal | internalMappable | intro | introtitle | note | publication | text | title | internalConfigureView | psuedoStyle) #REQUIRED
	structure (body | heading) #IMPLIED
	use (chapter | verse | prose | proseSentenceInitial | line | lineSentenceInitial | list | table | footnote | stanzabreak | title | properNoun | special) #IMPLIED
	type (character | paragraph) #REQUIRED
	basedOn IDREF #IMPLIED
>
<!ELEMENT sfm (#PCDATA)>
<!ATTLIST sfm
	paraStyleContext IDREF #IMPLIED>
<!ELEMENT sfmchar (#PCDATA)>
<!ELEMENT usage (#PCDATA)>
<!ATTLIST usage
	wsId CDATA #REQUIRED
>
<!ELEMENT help EMPTY>
<!ATTLIST help
	category CDATA #IMPLIED
	topic CDATA #IMPLIED
>
<!ELEMENT font (override*)>
<!ATTLIST font
	size CDATA #IMPLIED
	bold (true | false) #IMPLIED
	italic (true | false) #IMPLIED
	color CDATA #IMPLIED
	underlineColor CDATA #IMPLIED
	superscript (true | false) #IMPLIED
	subscript (true | false) #IMPLIED
	dropCap CDATA #IMPLIED
	smallCaps (true | false) #IMPLIED
	underline (none | single | double | dotted | dashed | squiggle | strikethrough) #IMPLIED
	spellcheck (true | false) #IMPLIED
>
<!ELEMENT override EMPTY>
<!ATTLIST override
	wsId CDATA #REQUIRED
	size CDATA #IMPLIED
	family CDATA #IMPLIED
>
<!ELEMENT paragraph EMPTY>
<!ATTLIST paragraph
	basedOn IDREF #IMPLIED
	next IDREF #IMPLIED
	alignment (left | center | right | full) #IMPLIED
	background CDATA #IMPLIED
	indentLeft CDATA #IMPLIED
	indentRight CDATA #IMPLIED
	lineSpacing CDATA #IMPLIED
	lineSpacingType (atleast | exact | rel) 'atleast'
	firstLine CDATA #IMPLIED
	hanging CDATA #IMPLIED
	spaceBefore CDATA #IMPLIED
	spaceAfter CDATA #IMPLIED
	border (top | bottom | leading | trailing) #IMPLIED
	keepWithNext (true | false) #IMPLIED
	keepTogether (true | false) #IMPLIED
	widowOrphan (true | false) #IMPLIED
	bulNumScheme CDATA #IMPLIED
	bulNumStartAt CDATA #IMPLIED
>
<!ELEMENT replacements (change*)>
<!ELEMENT change EMPTY>
<!ATTLIST change
	old CDATA #REQUIRED
	new IDREF #REQUIRED
>
<!ELEMENT ImportMappingSets (ImportMapping+)>
<!ELEMENT ImportMapping (mapping+)>
<!ATTLIST ImportMapping
	name CDATA #IMPLIED
>
<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
	id CDATA #REQUIRED
	type (style | property | excluded) #REQUIRED
	propertyName (DefaultParagraphCharacters | ChapterLabel | Figure | FigureFilename | FigureCaption |
	FigureCopyright | FigureDescription | FigureLayoutPosition | FigureRefRange | FigureScale |
	TitleShort | DefaultFootnoteCharacters) #IMPLIED
	styleName IDREF #IMPLIED
>

=== JamesPrabu/liblcm/tests/SIL.LCModel.Tests/TestData/TeStyles.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Styles SYSTEM "../../../src/SIL.LCModel/Styles.dtd">
<!-- IMPORTANT NOTE TO MAINTAINERS
	*********************************************************************************************
	ANY change to this Stylesheet must be accompanied by the generation of a new version using
	guidgen. Be sure to validate any changes against Styles.dtd.
	*********************************************************************************************
-->
<Styles date="2016-02-28" DTDver="1610190E-D7A3-42D7-8B48-C0C49320435F" label="Scripture">
	<markup version="04D4DC0C-9754-4072-BFE7-DE116967732B">
		<tag id="Abbreviation" guid="0225A2C8-0803-4E40-921A-2CBD97C13018" userlevel="3" context="general" type="character">
			<usage wsId="en">Abbreviation identifies an abbreviation (usually in a note or introduction).</usage>
			<help category="Special_Text_and_Character_Styles"/>
			<font smallCaps="true"/>
		</tag>
	</markup>
	<replacements />
	<ImportMappingSets>
		<ImportMapping name="TE Default">
			<mapping id="c" type="style" styleName="Chapter_Number" />
			<mapping id="cap" type="property" propertyName="FigureCaption" />
			<mapping id="cat" type="property" propertyName="FigureFilename" />
			<mapping id="f" type="style" styleName="Note_General_Paragraph" />
			<mapping id="gmb" type="property" propertyName="FigureFilename" /> <!--From Indonesia branch standard-->
			<mapping id="gmbj" type="property" propertyName="FigureCaption" /> <!--From Indonesia branch standard-->
			<mapping id="h" type="property" propertyName="TitleShort" />
			<mapping id="p" type="style" styleName="Paragraph" />
			<mapping id="rem" type="style" styleName="Remark" />
			<mapping id="vt" type="property" propertyName="DefaultParagraphCharacters" />
		</ImportMapping>
	</ImportMappingSets>
</Styles>

=== JamesPrabu/liblcm/Src/FDO/FDOTests/TestData/TeStyles.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE Styles SYSTEM "../../../../DistFiles/Styles.dtd">
<!-- IMPORTANT NOTE TO MAINTAINERS
	*********************************************************************************************
	ANY change to this Stylesheet must be accompanied by the generation of a new version using
	guidgen. Be sure to validate any changes against Styles.dtd.
	*********************************************************************************************
-->
<Styles date="2016-02-28" DTDver="1610190E-D7A3-42D7-8B48-C0C49320435F" label="Scripture">
	<ImportMappingSets>
		<ImportMapping name="TE Default">
			<mapping id="c" type="style" styleName="Chapter_Number" />
			<mapping id="cap" type="property" propertyName="FigureCaption" />
			<mapping id="cat" type="property" propertyName="FigureFilename" />
			<mapping id="f" type="style" styleName="Note_General_Paragraph" />
			<mapping id="gmb" type="property" propertyName="FigureFilename" /> <!--From Indonesia branch standard-->
			<mapping id="gmbj" type="property" propertyName="FigureCaption" /> <!--From Indonesia branch standard-->
			<mapping id="h" type="property" propertyName="TitleShort" />
			<mapping id="p" type="style" styleName="Paragraph" />
			<mapping id="rem" type="style" styleName="Remark" />
			<mapping id="vt" type="property" propertyName="DefaultParagraphCharacters" />
		</ImportMapping>
	</ImportMappingSets>
</Styles>
